# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5f0fde849556ce02927a6ac62aa974c86563287dde00be21098047b5c24a579598535cb392215eca9c79ad2fbdf54fb86fd4a6d2a7f3458a5963bebc335beba

test:
  secret_key_base: 1e049ba46b47d1f1c9acad100867bb3732dacb158c5ad0ca4eb80ea6356a5ada75bc9b0ec9a626a7e0f809929ff64b7d2aac011f40b03a340620c3b20383f007

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
